name: Deploy APKs

on:
  push:
    branches:
      - main  # Run only when pushing to the main branch
    paths:
      - 'MC/*.apk'
      - 'SIL/*.apk'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least the last two commits

      - name: Identify changed APKs
        id: changed_files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD -- '*.apk' || true)
          echo "Changed files: $CHANGED"
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            if [[ "${{ env.CHANGED_FILES }}" == *"MC/"* ]]; then
              echo "Deploying MC.apk..."
              scp MC/*.apk ${{ secrets.USERNAME }}@${{ secrets.IP }}://path/MC/
            fi

            if [[ "${{ env.CHANGED_FILES }}" == *"SIL/"* ]]; then
              echo "Deploying SIL.apk..."
              scp SIL/*.apk ${{ secrets.USERNAME }}@${{ secrets.IP }}:/var/www/html/SIL/
            fi
