name: Deploy to EC2

on:
  push:
    branches:
      - main
      - production

jobs:
  checkout_mycode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy_to_qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check MC directory and deploy
        run: |
          if [ -d "$GITHUB_WORKSPACE/MC" ]; then
            echo "Deploying MC directory..."
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$GITHUB_WORKSPACE/MC"/* mutuwa@${{ secrets.SERVER_HOST }}:/var/www/html/SIL/
          else
            echo "MC directory not found, skipping deployment..."
          fi

      - name: Check SIL directory and deploy
        run: |
          if [ -d "$GITHUB_WORKSPACE/SIL" ]; then
            echo "Deploying SIL directory..."
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$GITHUB_WORKSPACE/SIL"/* mutuwa@${{ secrets.SERVER_HOST }}:/var/www/html/SIL/
          else
            echo "SIL directory not found, skipping deployment..."
          fi


  deploy_to_prod:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Production deployment started..."
          # Add commands for production deployment if needed

