name: Deploy to EC2

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get changes for MC directory
        id: check_mc
        run: |
          # Check if there are any changes in the MC directory
          echo "Checking for changes in the MC directory..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^MC/" || echo "No changes in MC directory"
        
      - name: Deploy MC directory if changed
        if: steps.check_mc.outputs.result != 'No changes in MC directory'
        run: |
          echo "Deploying MC directory..."
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$GITHUB_WORKSPACE/MC"/* mutuwa@${{ secrets.SERVER_HOST }}:/var/www/html/Mobile/MC/

      - name: Get changes for SIL directory
        id: check_sil
        run: |
          # Check if there are any changes in the SIL directory
          echo "Checking for changes in the SIL directory..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^SIL/" || echo "No changes in SIL directory"

      - name: Deploy SIL directory if changed
        if: steps.check_sil.outputs.result != 'No changes in SIL directory'
        run: |
          echo "Deploying SIL directory..."
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$GITHUB_WORKSPACE/SIL"/* mutuwa@${{ secrets.SERVER_HOST }}:/var/www/html/Mobile/SIL/
