name: Deploy APKs

on:
  push:
    branches:
      - main
    paths:
      - 'MC/**'
      - 'SIL/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all file history is available

      # Step 2: Print directory structure at the root level
      - name: Print root directory structure
        run: |
          echo "Root directory structure of the GitHub workspace:"
          tree /home/runner/work/mobile/mobile -L 2  # Adjust the depth level to show two levels

      # Step 3: Print the first few files at the root of the repository
      - name: Print first few files
        run: |
          echo "First few files in the repository (root level):"
          ls -lh /home/runner/work/mobile/mobile | head -n 10  # List the first 10 files in the root directory

      # Step 4: Identify changed files
      - name: Identify changed files
        id: changed_files
        run: |
          # Get the list of changed files from the previous commit to the current one
          CHANGED=$(git diff --name-only HEAD^ HEAD -- 'MC/**' 'SIL/**' || true)
          echo "Changed files: $CHANGED"
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      # Step 5: Debugging: Print working directories and check existence
      - name: Debugging Print working directories
        run: |
          echo "GitHub Workspace: /home/runner/work/mobile/mobile"
          echo "MC directory: /home/runner/work/mobile/mobile/MC"
          echo "SIL directory: /home/runner/work/mobile/mobile/SIL"

          # Check if the MC directory exists
          if [ -d "/home/runner/work/mobile/mobile/MC" ]; then
            echo "MC directory exists."
          else
            echo "Error: MC directory does not exist."
            exit 1
          fi

          # Check if the SIL directory exists
          if [ -d "/home/runner/work/mobile/mobile/SIL" ]; then
            echo "SIL directory exists."
          else
            echo "Error: SIL directory does not exist."
            exit 1
          fi

      # Step 6: Deploy to Server using SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Changed files: ${{ env.CHANGED_FILES }}"
            ls -R /home/runner/work/mobile/mobile

            # Deploy files from MC directory if there are changes
            if [[ "${{ env.CHANGED_FILES }}" == *"MC/"* ]]; then
              echo "Deploying files in MC directory..."
              cd /home/runner/work/mobile/mobile/MC
              echo "Current working directory (MC): $(pwd)"
              ls -l  # List MC directory contents for debugging

              # Deploy all changed files in the MC folder
              for file in *; do
                if [[ -f "$file" ]]; then
                  echo "Deploying $file to /server/path/MC/"
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/MC/
                fi
              done
            fi

            # Deploy files from SIL directory if there are changes
            if [[ "${{ env.CHANGED_FILES }}" == *"SIL/"* ]]; then
              echo "Deploying files in SIL directory..."
              cd /home/runner/work/mobile/mobile/SIL
              echo "Current working directory (SIL): $(pwd)"
              ls -l  # List SIL directory contents for debugging

              # Deploy all changed files in the SIL folder
              for file in *; do
                if [[ -f "$file" ]]; then
                  echo "Deploying $file to /server/path/SIL/"
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/SIL/
                fi
              done
            fi
