name: Deploy APKs

on:
  push:
    branches:
      - main  # Run only when pushing to the main branch
    paths:
      - 'MC/*.apk'
      - 'SIL/*.apk'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least the last two commits

      - name: Identify changed APKs
        id: changed_files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD -- '*.apk' || true)
          echo "Changed files: $CHANGED"
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy MC APK if changed
        if: contains(env.CHANGED_FILES, 'MC/')
        run: |
          echo "Deploying MC.apk..."
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no MC/*.apk ${{ secrets.USERNAME }}@${{ secrets.IP }}:/var/www/html/MC/

      - name: Deploy SIL APK if changed
        if: contains(env.CHANGED_FILES, 'SIL/')
        run: |
          echo "Deploying SIL.apk..."
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no SIL/*.apk ${{ secrets.USERNAME }}@${{ secrets.IP }}:/var/www/html/SIL/
