name: Deploy APKs

on:
  push:
    branches:
      - main
    paths:
      - 'MC/**'
      - 'SIL/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire history to ensure all files are checked out

      - name: Identify changed files
        id: changed_files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD -- 'MC/**' 'SIL/**' || true)
          echo "Changed files: $CHANGED"
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      - name: Print directory structure of GitHub workspace
        run: |
          echo "Printing directory structure of GitHub workspace:"
          # Print full directory structure of the workspace
          tree $GITHUB_WORKSPACE

      - name: Debugging: Print working directories
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Remote path for MC: /server/path/MC/"
          echo "Remote path for SIL: /server/path/SIL/"

          # Print the contents of MC directory if it exists
          if [ -d "$GITHUB_WORKSPACE/MC" ]; then
            echo "Contents of MC directory: $(ls -l $GITHUB_WORKSPACE/MC)"
          else
            echo "MC directory does not exist."
          fi

          # Print the contents of SIL directory if it exists
          if [ -d "$GITHUB_WORKSPACE/SIL" ]; then
            echo "Contents of SIL directory: $(ls -l $GITHUB_WORKSPACE/SIL)"
          else
            echo "SIL directory does not exist."
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Changed files: ${{ env.CHANGED_FILES }}"

            # Check if there are changes in the MC directory
            if [[ "${{ env.CHANGED_FILES }}" == *"MC/"* ]]; then
              echo "Deploying files in MC directory..."
              
              # Ensure we're in the right directory inside the GitHub workspace
              cd $GITHUB_WORKSPACE/MC
              echo "Current working directory (MC): $(pwd)"
              ls -l  # List MC directory contents for debugging
              
              # Deploy all APK files in the MC folder
              for file in *; do
                if [[ -f "$file" ]]; then
                  echo "Deploying $file to /server/path/MC/"
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/MC/
                fi
              done
            fi

            # Check if there are changes in the SIL directory
            if [[ "${{ env.CHANGED_FILES }}" == *"SIL/"* ]]; then
              echo "Deploying files in SIL directory..."
              
              # Ensure we're in the right directory inside the GitHub workspace
              cd $GITHUB_WORKSPACE/SIL
              echo "Current working directory (SIL): $(pwd)"
              ls -l  # List SIL directory contents for debugging
              
              # Deploy all APK files in the SIL folder
              for file in *; do
                if [[ -f "$file" ]]; then
                  echo "Deploying $file to /server/path/SIL/"
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/SIL/
                fi
              done
            fi
