name: Deploy APKs

on:
  push:
    branches:
      - main  # Run only when pushing to the main branch
    paths:
      - 'MC/**'
      - 'SIL/**'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire history to ensure all files are checked out

      - name: Identify changed files
        id: changed_files
        run: |
          # Get the list of changed files
          CHANGED=$(git diff --name-only HEAD^ HEAD -- 'MC/**' 'SIL/**' || true)
          echo "Changed files: $CHANGED"
          # Ensure that CHANGED_FILES environment variable is set correctly
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      - name: Debug - List repository structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing directory structure:"
          ls -R  # List the entire repository structure for debugging

      - name: Debug - List MC directory
        run: |
          echo "Contents of MC/ directory:"
          ls -l $GITHUB_WORKSPACE/MC/  # Fix path reference

      - name: Debug - List SIL directory
        run: |
          echo "Contents of SIL/ directory:"
          ls -l $GITHUB_WORKSPACE/SIL/  # Fix path reference

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Changed files: ${{ env.CHANGED_FILES }}"

            # Check if there are changes in the MC directory
            if [[ "${{ env.CHANGED_FILES }}" == *"MC/"* ]]; then
              echo "Deploying files in MC directory..."
              # Ensure we're in the right directory inside the GitHub workspace
              cd $GITHUB_WORKSPACE/MC
              echo "Current working directory (MC): $(pwd)"
              ls -l  # List MC directory contents for debugging
              # Deploy all changed files in the MC folder (any file, not just .apk)
              for file in *; do
                if [[ -f "$file" ]]; then
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/MC/
                fi
              done
            fi

            # Check if there are changes in the SIL directory
            if [[ "${{ env.CHANGED_FILES }}" == *"SIL/"* ]]; then
              echo "Deploying files in SIL directory..."
              # Ensure we're in the right directory inside the GitHub workspace
              cd $GITHUB_WORKSPACE/SIL
              echo "Current working directory (SIL): $(pwd)"
              ls -l  # List SIL directory contents for debugging
              # Deploy all changed files in the SIL folder (any file, not just .apk)
              for file in *; do
                if [[ -f "$file" ]]; then
                  scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/SIL/
                fi
              done
            fi
