name: Deploy Files to Server

on:
  push:
    branches:
      - main  # Trigger this on push to the main branch (or use whichever branch you prefer)
    paths:
      - 'MC/*'    # Triggers if any files in MC directory are modified
      - 'SIL/*'   # Triggers if any files in SIL directory are modified

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # or use your port if different
          script: |

            
            # Debugging: Print working directories
            echo "GitHub Workspace: $GITHUB_WORKSPACE"
            echo "Remote path for MC: /server/path/MC/"
            echo "Remote path for SIL: /server/path/SIL/"

            # Check if the local MC directory exists
            if [ ! -d "$GITHUB_WORKSPACE/mobile/MC" ]; then
              echo "Error: MC directory does not exist in local workspace"
              exit 1
            fi

            # Check if the local SIL directory exists
            if [ ! -d "$GITHUB_WORKSPACE/mobile/sil" ]; then
              echo "Error: SIL directory does not exist in local workspace"
              exit 1
            fi

            # Check and create MC directory on the remote server if it doesn't exist
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "if [ ! -d /server/path/MC ]; then echo 'MC directory does not exist on server'; mkdir -p /server/path/MC; fi"

            # Check and create SIL directory on the remote server if it doesn't exist
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "if [ ! -d /server/path/SIL ]; then echo 'SIL directory does not exist on server'; mkdir -p /server/path/SIL; fi"

            # Deploy MC files to the remote server
            echo "Deploying files from MC directory..."
            for file in $GITHUB_WORKSPACE/mobile/mobileMC/*; do
              if [ -f "$file" ]; then
                echo "Deploying $file to server..."
                scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/MC/
              fi
            done

            # Deploy SIL files to the remote server
            echo "Deploying files from SIL directory..."
            for file in $GITHUB_WORKSPACE/SIL/*; do
              if [ -f "$file" ]; then
                echo "Deploying $file to server..."
                scp "$file" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/SIL/
              fi
            done

            echo "Deployment completed successfully."
