name: Deploy Changes to Server

on:
  push:
    paths:
      - 'MC/**'
      - 'SIL/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH to connect to your server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install rsync (needed for file transfer)
      - name: Install rsync
        run: sudo apt-get install -y rsync

      # Step 4: Check for changes in MC and copy files over
      - name: Copy MC files
        if: ${{ github.event.head_commit.modified == 'MC' }}
        run: |
          echo "Copying MC files to the server..."
          rsync -avz --exclude '.git' ./MC/ user@your-server:/path/to/your/app/MC/

      # Step 5: Check for changes in SIL and copy files over
      - name: Copy SIL files
        if: ${{ github.event.head_commit.modified == 'SIL' }}
        run: |
          echo "Copying SIL files to the server..."
          rsync -avz --exclude '.git' ./SIL/ user@your-server:/path/to/your/app/SIL/
