name: Deploy APKs

on:
  push:
    branches:
      - main  # Run only when pushing to the main branch
    paths:
      - 'MC/**'
      - 'SIL/**'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire history to ensure all files are checked out

      - name: Identify changed files
        id: changed_files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD -- 'MC/**' 'SIL/**' || true)
          echo "Changed files: $CHANGED"
          # Ensure that CHANGED_FILES environment variable is set correctly
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV

      - name: Debug - List repository structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing directory structure:"
          ls -R  # List the entire repository structure for debugging

      - name: Debug - List MC directory
        run: |
          echo "Contents of MC/ directory:"
          ls -l MC/

      - name: Debug - List SIL directory
        run: |
          echo "Contents of SIL/ directory:"
          ls -l SIL/

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Changed files: ${{ env.CHANGED_FILES }}"

            # Deploy MC APK if there are any changes in the MC folder
            if [[ "${{ env.CHANGED_FILES }}" == *"MC/"* ]]; then
              echo "Deploying MC.apk..."
              # Change to the correct directory inside the GitHub workspace
              cd $GITHUB_WORKSPACE/MC
              echo "Current working directory (MC): $(pwd)"
              ls -l  # List MC directory contents for debugging
              # Deploy all APK files in the MC folder
              scp * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/MC/
            fi

            # Deploy SIL APK if there are any changes in the SIL folder
            if [[ "${{ env.CHANGED_FILES }}" == *"SIL/"* ]]; then
              echo "Deploying SIL.apk..."
              # Change to the SIL directory before listing and deploying files
              cd $GITHUB_WORKSPACE/SIL
              echo "Current working directory (SIL): $(pwd)"
              ls -l  # List SIL directory contents for debugging
              # Deploy all files in the SIL folder
              scp * ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/server/path/SIL/
            fi
